
name: Deploy to Cloud Run 

on:
  push:
    branches:
      - main  # Run this workflow only when pushing to main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: myapp1  # Name of your Cloud Run service
  REGION: us-central1  # Change to your desired region

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud CLI
      run: gcloud auth configure-docker

    - name: Build and Tag Docker Image
      run: |
        docker build -f ./Dockerfile -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest .

    - name: Push Docker Image to Google Container Registry
      run: |
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated
